app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

show-district:
    pattern:  /{id}/district.{format}
    defaults: { _controller: "AppBundle:Ad:showDistrict", format: html }
    requirements:
        format: json    
