# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    appbundle.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: 'kernel.event_listener', event: oneup_uploader.post_persist, method: onUpload }
           
    myCompany.form.flow.createVehicle:
        class: AppBundle\Form\CreateVehicleFlow
        parent: craue.form.flow
        scope: request
        
#        
#    listener.requestresponse:
#        class: AppBundle\EventListener\UploadListener
#        tags:
#         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }
#         - { name: kernel.event_listener, event: kernel.response, method: onUpload }