<?php

namespace AppBundle\Entity;

/**
 * AdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository {

    public function queryOwnedBy($cityId) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.city = :city_id')
                ->setParameter('city_id', $cityId);


        return $qb->getQuery()
                        ->getArrayResult();
    }

}
