<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function findAllUserEnabled($enabled = true) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC');

        if (false === is_null($enabled)) {
            $qb->andWhere('c.enabled = :enabled')
                    ->setParameter('enabled', $enabled);

            return $qb->getQuery()
                            ->getResult();
        }
    }
        public function findAllUserdisabled($enabled = false) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC');

        if (false === is_null($enabled)) {
            $qb->andWhere('c.enabled = :enabled')
                    ->setParameter('enabled', $enabled);

            return $qb->getQuery()
                            ->getResult();
        }
    }

}
